# For automation only, do not use it in manual testing
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: name-example
spec:
  desiredState:
    interfaces:
      - name: br-name-example
        description: Linux bridge as a port
        type: linux-bridge
        state: up
        ipv4:
          enabled: false
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: eth1-example
